name: Deploy HTML Project to GitHub Pages

on:
  push:
    branches:
      - main  # Executa o workflow em pushes na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout the repository
        uses: actions/checkout@v3

      # 2. Publica os arquivos no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: ./siteada  # Publica o diretório raiz, incluindo /css, /img, /js e index.html
